### ISSUE TITLE
**NRPE: Unable to read output** 

### ISSUE THREAD

**Issue by kaushalshriyan** [NagiosEnterprises/nrpe#149]
I am facing the below issue while invoking the below command from the Nagios Monitoring server.

[root@app01 log]# rpm -qa | grep nagios
**nagios-plugins-2.2.0-1.x86_64**
[root@app01 log]# rpm -qa | grep nrpe
**nrpe-3.2.0-1.x86_64
nrpe-plugin-3.2.0-1.x86_64**
[root@app01 log]# cat /etc/redhat-release
**CentOS Linux release 7.3.1611 (Core)**
[root@app01 log]#

```
 
/usr/lib/nagios/plugins/check_nrpe -H 172.26.21.5
NRPE v3.2.0
/usr/lib/nagios/plugins/check_nrpe -H 172.26.21.5 -c check_users
**NRPE: Unable to read output**

Jul 11 20:23:01 int-app01 nrpe[4898]: CONN_CHECK_PEER: checking if host is allowed: 172.26.24.8 port 53936
Jul 11 20:23:01 int-app01 nrpe[4898]: Connection from 172.26.24.8 port 53936
Jul 11 20:23:01 int-app01 nrpe[4898]: is_an_allowed_host (AF_INET): is host >172.26.24.8< an allowed host >172.26.24.8<
Jul 11 20:23:01 int-app01 nrpe[4898]: is_an_allowed_host (AF_INET): is host >172.26.24.8< an allowed host >172.26.24.8<
Jul 11 20:23:01 int-app01 nrpe[4898]: is_an_allowed_host (AF_INET): host is in allowed host list!
Jul 11 20:23:01 int-app01 nrpe[4898]: Host address is in allowed_hosts
Jul 11 20:23:01 int-app01 nrpe[4898]: Host 172.26.24.8 is asking for command 'check_users' to be run...
Jul 11 20:23:01 int-app01 nrpe[4898]: Running command: /usr/lib/nagios/plugins/check_users -w 5 -c 10
Jul 11 20:23:01 int-app01 nrpe[4899]: ERROR: my_system() seteuid(0): Operation not permitted, bailing out...
Jul 11 20:23:01 int-app01 nrpe[4898]: Command completed with return code 2 and output:
Jul 11 20:23:01 int-app01 nrpe[4898]: Return Code: 3, Output: NRPE: Unable to read output
Jul 11 20:23:01 int-app01 nrpe[4898]: Connection from 172.26.24.8 closed.
```

**Comment by hedenface** [comment]
This should actually already be fixed... I screwed up with 3.2.0. I made some changes, and issued a release, and then had to fix ***that*** bug, and just issued a re-release. Something like that isn't going to happen again, but in the meantime we're stuck with something like this. So, my apologies for that.

If you compile from the latest source here on GitHub, does the error persist?

**Comment by shriyankaushal** [comment]
@hedenface I am facing issue while i am building rpm binary

`+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: nrpe-3.2.0-1.x86_64
warning: %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/etc/nagios
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.MLuu2S
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd nrpe-3.2.0
+ DOCDIR=/root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0
+ export DOCDIR
+ /usr/bin/mkdir -p /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0
+ cp -pr Changelog /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0
cp: cannot stat 'Changelog': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.MLuu2S (%doc)
warning: %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0


RPM build errors:
    %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/etc/nagios
    Bad exit status from /var/tmp/rpm-tmp.MLuu2S (%doc)
    %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0`
  
Details are as below 
rpmbuild -ba nrpe.spec -> http://sprunge.us/XiNS?eng 
cat nrpe.spec -> http://sprunge.us/LZJb?eng

**Comment by kaushalshriyan** [comment]
@hedenface  I am facing issue while i am building rpm binary

`+ /usr/lib/rpm/check-buildroot

/usr/lib/rpm/redhat/brp-compress
/usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
/usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
/usr/lib/rpm/redhat/brp-python-hardlink
/usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: nrpe-3.2.0-1.x86_64
warning: %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/etc/nagios
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.MLuu2S
umask 022
cd /root/rpmbuild/BUILD
cd nrpe-3.2.0
DOCDIR=/root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0
export DOCDIR
/usr/bin/mkdir -p /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0
cp -pr Changelog /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0
cp: cannot stat 'Changelog': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.MLuu2S (%doc)
warning: %defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0
RPM build errors:
%defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/etc/nagios
Bad exit status from /var/tmp/rpm-tmp.MLuu2S (%doc)
%defattr doesn't define directory mode so file mode defined in %defattr is used for directory: /root/rpmbuild/BUILDROOT/nrpe-3.2.0-1.x86_64/usr/share/doc/nrpe-3.2.0`

Details are as below
rpmbuild -ba nrpe.spec -> http://sprunge.us/XiNS?eng
cat nrpe.spec -> http://sprunge.us/LZJb?eng

**Comment by shriyankaushal** [comment]
@hedenface Please do let me know if you need any additional details

**Comment by hedenface** [comment]
@shriyankaushal You didn't answer my question really. Is your build process from the ***very latest*** pull of the master branch here on GitHub? Or did you grab this several days ago? Or from a different source?

**Comment by shriyankaushal** [comment]
@hedenface yes i did pulled it from the latest version https://github.com/NagiosEnterprises/nrpe/blob/master/update-version
https://github.com/NagiosEnterprises/nrpe

`NRPE Changelog
==============

[3.2.0](https://github.com/NagiosEnterprises/nrpe/releases/tag/nrpe-3.2.0) - 2017-06-26
---------------------------------------------------------------------------------------
**ENHANCEMENTS**
* Added max_commands definition to nrpe.cfg to rate limit simultaneous fork()ed children (Bryan Heden)
* Added -E, --stderr-to-stdout options for check_nrpe to redirect output (Bryan Heden)
* Added support for Gentoo init (Troy Lea @box293)
* Cleaned up code a bit, updated readmes and comments across the board (Bryan Heden)
* Added -V, --version to nrpe and fixed the output (Bryan Heden)
* Added different SSL error messages to be able to pinpoint where some SSL errors occured (Bryan Heden)
* Updated logic in al parse_allowed_hosts (Bryan Heden)
* Added builtin OpenSSL Engine support where available (Bryan Heden + @skrueger8)
* Clean up compilation warnings (Bryan Heden)
* Added more commented commands in nrpe.cfg (Bryan Heden)

**FIXES**
* Undefined check returns UNKNOWN (Bryan Heden)
* Fix incompatibility with OpenSSL 1.1.0 via SECLEVEL distinction (Bryan Heden)
* Fix ipv4 error in logfile even if address is ipv6 (Bryan Heden)
* Fix improper valid/invalid certificate warnings (Bryan Heden)`

**Comment by hedenface** [comment]
Is the same version on the remote host?

**Comment by shriyankaushal** [comment]
@hedenface yes it is the same version

**Comment by hedenface** [comment]
Are you able to walk me through the *entire process* of ***your*** RPM building? 

As it sits, when I pull the code, run `autoconf && ./configure && make install` ..etc.. I am unable to reproduce your issue using this method.

**Comment by shriyankaushal** [comment]
@hedenface please find the details here -> http://sprunge.us/VWDD

**Comment by hedenface** [comment]
Ok. I didn't update the nrpe.spec file when I pushed my latest changes. To be quite honest, I wasn't aware that it needed changed (consider me an extreme n00b when it comes to packaging).

But I must thank you @shriyankaushal because I've learned more from your latest details than all of the rpm packaging I've ever read.

So, just to be clear, here is what I encountered:

I spun up a new Cent7 box, installed the required dependencies and followed your instructions to the letter.

It did not build an RPM for me, so I checked the errors, and updated the word `Changelog` to `CHANGELOG.md` in the spec file, and then rebuilt. Once I did that, it was fine!

Can you perform those same updates and rebuild?

```
sed -i 's/Changelog/CHANGELOG.md/' nrpe.spec
```

Let me know if it works!

**Comment by kaushalshriyan** [comment]
@hedenface I still see ERROR: my_system() seteuid(0): Operation not permitted in /var/log/nrpe.log 

[root@int-test01 ~]# ps aux | grep -v grep | grep nrpe
**nagios    4665  0.0  0.0  42112  2724 ?        Ss   18:28   0:00 /usr/sbin/nrpe -c /etc/nagios/nrpe.cfg -f**
[root@int-hotel01 ~]#
[root@int-test01 ~]# rpm -qa | grep nagios
nagios-plugins-2.2.1-1.x86_64
[root@int-test01 ~]# rpm -qa | grep nrpe
nrpe-3.2.0-1.x86_64
nrpe-plugin-3.2.0-1.x86_64
[root@int-test01 ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@int-test01 ~]#

```
Jul 19 18:28:47 int-test01 nrpe[4550]: Caught SIGTERM - shutting down...
Jul 19 18:28:47 int-test01 nrpe[4550]: ERROR: remove_pid_file() seteuid(0): Operation not permitted
Jul 19 18:28:47 int-test01 nrpe[4550]: Daemon shutdown
Jul 19 18:28:47 int-test01 nrpe[4665]: Starting up daemon
Jul 19 18:28:47 int-test01 nrpe[4665]: Server listening on 0.0.0.0 port 5666.
Jul 19 18:28:47 int-test01 nrpe[4665]: Server listening on :: port 5666.
Jul 19 18:28:47 int-test01 nrpe[4665]: Listening for connections on port 5666
Jul 19 18:28:47 int-test01 nrpe[4665]: Allowing connections from: 127.0.0.1,172.26.24.8
Jul 19 18:28:54 int-test01 nrpe[4671]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:29:00 int-test01 nrpe[4678]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:29:01 int-test01 nrpe[4684]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:29:23 int-test01 nrpe[4697]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:29:54 int-test01 nrpe[4728]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:30:01 int-test01 nrpe[4738]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:30:01 int-test01 nrpe[4742]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:30:24 int-test01 nrpe[4752]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:30:53 int-test01 nrpe[4779]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:31:01 int-test01 nrpe[4787]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:31:01 int-test01 nrpe[4791]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 18:31:23 int-test01 nrpe[4796]: ERROR: my_system() seteuid(0): Operation not permitted
```

**Comment by hedenface** [comment]
I'm very sorry, but I am not able to reproduce this issue. I am not having these issues.

I have a fully working and installed built RPM for NRPE, and when using the `check_nrpe` (that I compiled from source) and running the `check_nrpe` plugin against the NRPE running (the RPM one I ***just installed***) everything is fine and I do not have these warnings.

And as I've stated previously - I have updated the `my_system() setuid(0)` ERROR to be a warning - this tells me that for whatever reason, you are ***not running the latest version of NRPE***. It seems likely (and I may be wrong) that perhaps your build failed previously, and you're still using the version built before your latest attempts?

**Comment by kaushalshriyan** [comment]
@hedenface I have set it up on a new VM machine running CentOS Linux release 7.3.1611 (Core) and i still see the error

```
Jul 19 19:14:05 p4p-28-97 nrpe[19643]: ERROR: remove_pid_file() seteuid(0): Operation not permitted
Jul 19 19:14:31 p4p-28-97 nrpe[19709]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 19:15:01 p4p-28-97 nrpe[19737]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 19:15:01 p4p-28-97 nrpe[19743]: ERROR: my_system() seteuid(0): Operation not permitted
Jul 19 19:15:01 p4p-28-97 nrpe[19744]: ERROR: my_system() seteuid(0): Operation not permitted
```
```
[root@p4p-28-97 nagios]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@p4p-28-97 nagios]# rpm -qa | grep nagios
nagios-plugins-2.2.1-1.x86_64
[root@p4p-28-97 nagios]# rpm -qa | grep nagios^C
[root@p4p-28-97 nagios]# rpm -qil nagios-plugins-2.2.1-1.x86_64
Name        : nagios-plugins
Version     : 2.2.1
Release     : 1
Architecture: x86_64
Install Date: Wed Jul 19 19:10:34 2017
Group       : Applications/System
Size        : 3427072
License     : GPL
Signature   : (none)
Source RPM  : nagios-plugins-2.2.1-1.src.rpm
Build Date  : Wed Jul 19 18:23:26 2017
Build Host  : localhost
Relocations : /usr/lib/nagios/plugins
Packager    : Karl DeBisschop <kdebisschop@users.sourceforge.net>
Vendor      : Nagios Plugin Development Group
URL         : https://www.nagios-plugins.org/
Summary     : Host/service/network monitoring program plugins for Nagios
Description :

Nagios is a program that will monitor hosts and services on your
network, and to email or page you when a problem arises or is
resolved. Nagios runs on a unix server as a background or daemon
process, intermittently running checks on various services that you
specify. The actual service checks are performed by separate "plugin"
programs which return the status of the checks to Nagios. This package
contains those plugins.
/usr/lib/nagios/plugins/check_apt
/usr/lib/nagios/plugins/check_breeze
/usr/lib/nagios/plugins/check_by_ssh
/usr/lib/nagios/plugins/check_clamd
/usr/lib/nagios/plugins/check_cluster
/usr/lib/nagios/plugins/check_dhcp
/usr/lib/nagios/plugins/check_dig
/usr/lib/nagios/plugins/check_disk
/usr/lib/nagios/plugins/check_disk_smb
/usr/lib/nagios/plugins/check_dns
/usr/lib/nagios/plugins/check_dummy
/usr/lib/nagios/plugins/check_file_age
/usr/lib/nagios/plugins/check_flexlm
/usr/lib/nagios/plugins/check_fping
/usr/lib/nagios/plugins/check_ftp
/usr/lib/nagios/plugins/check_hpjd
/usr/lib/nagios/plugins/check_http
/usr/lib/nagios/plugins/check_icmp
/usr/lib/nagios/plugins/check_ide_smart
/usr/lib/nagios/plugins/check_ifoperstatus
/usr/lib/nagios/plugins/check_ifstatus
/usr/lib/nagios/plugins/check_imap
/usr/lib/nagios/plugins/check_ircd
/usr/lib/nagios/plugins/check_jabber
/usr/lib/nagios/plugins/check_ldap
/usr/lib/nagios/plugins/check_ldaps
/usr/lib/nagios/plugins/check_load
/usr/lib/nagios/plugins/check_log
/usr/lib/nagios/plugins/check_mailq
/usr/lib/nagios/plugins/check_mrtg
/usr/lib/nagios/plugins/check_mrtgtraf
/usr/lib/nagios/plugins/check_mysql
/usr/lib/nagios/plugins/check_mysql_query
/usr/lib/nagios/plugins/check_nagios
/usr/lib/nagios/plugins/check_nntp
/usr/lib/nagios/plugins/check_nntps
/usr/lib/nagios/plugins/check_nt
/usr/lib/nagios/plugins/check_ntp
/usr/lib/nagios/plugins/check_ntp_peer
/usr/lib/nagios/plugins/check_ntp_time
/usr/lib/nagios/plugins/check_nwstat
/usr/lib/nagios/plugins/check_oracle
/usr/lib/nagios/plugins/check_overcr
/usr/lib/nagios/plugins/check_pgsql
/usr/lib/nagios/plugins/check_ping
/usr/lib/nagios/plugins/check_pop
/usr/lib/nagios/plugins/check_procs
/usr/lib/nagios/plugins/check_real
/usr/lib/nagios/plugins/check_rpc
/usr/lib/nagios/plugins/check_sensors
/usr/lib/nagios/plugins/check_simap
/usr/lib/nagios/plugins/check_smtp
/usr/lib/nagios/plugins/check_snmp
/usr/lib/nagios/plugins/check_spop
/usr/lib/nagios/plugins/check_ssh
/usr/lib/nagios/plugins/check_ssmtp
/usr/lib/nagios/plugins/check_swap
/usr/lib/nagios/plugins/check_tcp
/usr/lib/nagios/plugins/check_time
/usr/lib/nagios/plugins/check_udp
/usr/lib/nagios/plugins/check_ups
/usr/lib/nagios/plugins/check_uptime
/usr/lib/nagios/plugins/check_users
/usr/lib/nagios/plugins/check_wave
/usr/lib/nagios/plugins/negate
/usr/lib/nagios/plugins/urlize
/usr/lib/nagios/plugins/utils.pm
/usr/lib/nagios/plugins/utils.sh
/usr/share/doc/nagios-plugins-2.2.1
/usr/share/doc/nagios-plugins-2.2.1/CODING
/usr/share/doc/nagios-plugins-2.2.1/COPYING
/usr/share/doc/nagios-plugins-2.2.1/ChangeLog
/usr/share/doc/nagios-plugins-2.2.1/FAQ
/usr/share/doc/nagios-plugins-2.2.1/INSTALL
/usr/share/doc/nagios-plugins-2.2.1/LEGAL
/usr/share/doc/nagios-plugins-2.2.1/README
/usr/share/doc/nagios-plugins-2.2.1/REQUIREMENTS
/usr/share/doc/nagios-plugins-2.2.1/SUPPORT
/usr/share/doc/nagios-plugins-2.2.1/THANKS
/usr/share/locale/de/LC_MESSAGES/nagios-plugins.mo
/usr/share/locale/fr/LC_MESSAGES/nagios-plugins.mo
[root@p4p-28-97 nagios]# rpm -qa | grep nrpe
nrpe-plugin-3.2.0-1.x86_64
nrpe-3.2.0-1.x86_64
nrpe-debuginfo-3.2.0-1.x86_64
[root@p4p-28-97 nagios]# rpm -qil nrpe-plugin-3.2.0-1.x86_64
Name        : nrpe-plugin
Version     : 3.2.0
Release     : 1
Architecture: x86_64
Install Date: Wed Jul 19 19:10:37 2017
Group       : Application/System
Size        : 79740
License     : GPL
Signature   : (none)
Source RPM  : nrpe-3.2.0-1.src.rpm
Build Date  : Wed Jul 19 18:09:18 2017
Build Host  : localhost
Relocations : /usr /usr/lib/systemd/system /etc/nagios
URL         : http://www.nagios.org
Summary     : Provides nrpe plugin for Nagios.
Description :
NPRE (Nagios Remote Plugin Executor) is a system daemon that
will execute various Nagios plugins locally on behalf of a
remote (monitoring) host that uses the check_nrpe plugin.
Various plugins that can be executed by the daemon are available
at: http://sourceforge.net/projects/nagiosplug

This package provides the server-side NRPE plugin for
Nagios-related applications.
/usr/lib/nagios/plugins
/usr/lib/nagios/plugins/check_nrpe
/usr/share/doc/nrpe-plugin-3.2.0
/usr/share/doc/nrpe-plugin-3.2.0/CHANGELOG.md
/usr/share/doc/nrpe-plugin-3.2.0/LEGAL
/usr/share/doc/nrpe-plugin-3.2.0/README.md
[root@p4p-28-97 nagios]# rpm -qil nrpe-3.2.0-1.x86_64
Name        : nrpe
Version     : 3.2.0
Release     : 1
Architecture: x86_64
Install Date: Wed Jul 19 19:10:37 2017
Group       : Application/System
Size        : 138052
License     : GPL
Signature   : (none)
Source RPM  : nrpe-3.2.0-1.src.rpm
Build Date  : Wed Jul 19 18:09:18 2017
Build Host  : localhost
Relocations : /usr /usr/lib/systemd/system /etc/nagios
URL         : http://www.nagios.org
Summary     : Host/service/network monitoring agent for Nagios
Description :
NPRE (Nagios Remote Plugin Executor) is a system daemon that
will execute various Nagios plugins locally on behalf of a
remote (monitoring) host that uses the check_nrpe plugin.
Various plugins that can be executed by the daemon are available
at: http://sourceforge.net/projects/nagiosplug

This package provides the client-side NRPE agent (daemon).
/etc/nagios
/etc/nagios/nrpe.cfg
/usr/lib/systemd/system/nrpe.service
/usr/lib/tmpfiles.d/nrpe.conf
/usr/sbin/nrpe
/usr/sbin/nrpe-uninstall
/usr/share/doc/nrpe-3.2.0
/usr/share/doc/nrpe-3.2.0/CHANGELOG.md
/usr/share/doc/nrpe-3.2.0/LEGAL
/usr/share/doc/nrpe-3.2.0/README.SSL.md
/usr/share/doc/nrpe-3.2.0/README.md
/usr/share/doc/nrpe-3.2.0/SECURITY.md
[root@p4p-28-97 nagios]# rpm -qil nrpe-debuginfo-3.2.0-1.x86_64
Name        : nrpe-debuginfo
Version     : 3.2.0
Release     : 1
Architecture: x86_64
Install Date: Wed Jul 19 19:10:37 2017
Group       : Development/Debug
Size        : 479177
License     : GPL
Signature   : (none)
Source RPM  : nrpe-3.2.0-1.src.rpm
Build Date  : Wed Jul 19 18:09:18 2017
Build Host  : localhost
Relocations : /usr /usr/lib/systemd/system /etc/nagios
URL         : http://www.nagios.org
Summary     : Debug information for package nrpe
Description :
This package provides debug information for package nrpe.
Debug information is useful when developing applications that use this
package or when debugging this package.
/usr/lib/debug
/usr/lib/debug/.build-id
/usr/lib/debug/.build-id/24
/usr/lib/debug/.build-id/24/a73f04226ad528acb33a27ab9370992e9ddff5
/usr/lib/debug/.build-id/24/a73f04226ad528acb33a27ab9370992e9ddff5.debug
/usr/lib/debug/.build-id/75
/usr/lib/debug/.build-id/75/0090e73b3dd58c9f6296a2a06cbf52955cc972
/usr/lib/debug/.build-id/75/0090e73b3dd58c9f6296a2a06cbf52955cc972.debug
/usr/lib/debug/.build-id/94
/usr/lib/debug/.build-id/94/c1c81295989b01ebe3025ff23af1453baa500e.debug
/usr/lib/debug/.dwz
/usr/lib/debug/.dwz/nrpe-3.2.0-1.x86_64
/usr/lib/debug/usr
/usr/lib/debug/usr/lib
/usr/lib/debug/usr/lib/nagios
/usr/lib/debug/usr/lib/nagios/plugins
/usr/lib/debug/usr/lib/nagios/plugins/check_nrpe.debug
/usr/lib/debug/usr/sbin
/usr/lib/debug/usr/sbin/nrpe.debug
/usr/src/debug/nrpe-3.2.0
/usr/src/debug/nrpe-3.2.0/include
/usr/src/debug/nrpe-3.2.0/include/acl.h
/usr/src/debug/nrpe-3.2.0/include/common.h
/usr/src/debug/nrpe-3.2.0/include/dh.h
/usr/src/debug/nrpe-3.2.0/include/nrpe.h
/usr/src/debug/nrpe-3.2.0/include/utils.h
/usr/src/debug/nrpe-3.2.0/src
/usr/src/debug/nrpe-3.2.0/src/acl.c
/usr/src/debug/nrpe-3.2.0/src/check_nrpe.c
/usr/src/debug/nrpe-3.2.0/src/nrpe.c
/usr/src/debug/nrpe-3.2.0/src/utils.c
[root@p4p-28-97 nagios]#
```

**Comment by djvongola** [comment]
i had a problem related only using the new nrpe version which was giving me the:
NRPE: Unable to read output

enabling debug on the remote host i obtained a slightly different output from the the one reported by @kaushalshriyan. (return code difference 2 instead of 3)

```
Command completed with return code 3 and output:
Code: 3, Output: NRPE: Unable to read output

```
the problem for me was on perl checks called with 'taint mode' 
> _The final safety net is the -T option. This option puts Perl into "taint mode." In this mode, Perl inherently distrusts any data that it receives from outside the program's source -- for example, data passed in on the command line, read from a file, or taken from CGI parameters.

changing ` #!/usr/bin/perl -wT` to `#!/usr/bin/perl -w` in the checks solved the problem. 
as i was saying before, this happened only after the upgrade to 3.1.1 (i'm using centos 6-7 systems), i have also installed 3.2.0 compiled from scratch but the problem was still present.

**Comment by hardstar** [comment]
Hi Team, 
I have similar issue , where are we changing "#!/usr/bin/perl -wT to #!/usr/bin/perl -w in the checks solved the problem."
please provide the file path.
 My server throws an error : ERROR: my_system() seteuid(0): Operation not permitted" when i run 
service nrpe status

**Comment by hedenface** [comment]
@kaushalshriyan as a follow up - are you still experiencing this issue?

@hardstar @djvongola - as I stated previously there were 2 releases of 3.2.0 on the same day (sorry) - so are you able to pull the very latest `master` here from git (or even better from `maint`) and compile and does the error go away?

I am still unable to reproduce this issue.

**Comment by hedenface** [comment]
I'm going to close the issue - although I was able to reproduce the problem after quite some testing - the fact is that the nagios-plugins package didn't install `check_users` for me where `nrpe` was expecting it.

Although I'm sure that the perl fix listed above works in some cases, for me all that was necessary to work was to update the command definitions in `nrpe.cfg` to update the plugins to their proper places, then restart nrpe, and all was well.

**Comment by signupforacomment** [comment]
Hi,

I'm aware the issue is closed, but reproducing it was quite easy. All that had to be done was that the specific NRPE plugin that was causing the pain had a shebang like:

```
#!/usr/bin/env perl
use warnings;
use whatever;
and so on
```

to have the plugin "portable" if Perl isn't installed in /usr/bin. The same issue applies to Python, Bash - basically everything.
Changing the first line to:

```
#!/usr/local/bin/perl
```

fixes it. This does not happen with the older NRPE 2.x version, as well as NRPE 3.0.x and I've been able to reproduce the issue on BSD and Linux, when running NRPE 3.2.x
