### ISSUE TITLE
nrpe dont_blame_nrpe no longer works

### ISSUE THREAD

**Issue by stanrate** [NagiosEnterprises/nrpe#177]
When nrpe.c was changed to cater for a V3 record, the code that checked for arguments was not changed to handle V3 records. As a result, the code does not work properly when a V3 record has been received.

The code needs to be changed

from
```
if (strchr(v2pkt->buffer, '!')) {
```
to
```
if (packet_ver == NRPE_PACKET_VERSION_2 && strchr(v2pkt->buffer, '!' || packet_ver == NRPE_PACKET_VERSION_3 && strchr(v3pkt->buffer, '!')) {
```
As a result of this bug, when check_nrpe is run, over 99% of the time nrpe allows arguments even though dont_blame_nrpe=0 has been specified. A second problem is that 1% of the time, when check_nrpe is run without an argument, nrpe reports that an argument has been supplied and logs the following two messages:
```
nrpe[xxxx]: Error: Request contained command arguments, but argument option is not enabled!
nrpe[xxxx]: Client request from was invalid, bailing out...
```
When I ran the following command on a Nagios server, the above two messages were not logged most of the time even though they should have been logged:
```
while date;do /usr/lib64/nagios/plugins/check_nrpe -H xxxx -c check_success -a my_arg;sleep 1;done
```
When I ran the following command on a Nagios server, the above two messages were intermittently and randomly logged about 1% of the time:
```
while date; do /usr/lib64/nagios/plugins/check_nrpe -H xxxx -c check_success; sleep 1;done
```
Thanks

**Comment by hedenface** [comment]
Thank you. I updated your comment for styling with markdown.

Are you willing to make these changes and submit a pull request?

**Comment by stanrate** [comment]
UNCLASSIFIED
Hi Bryan,

Sorry I have never made a pull request before and don't know what's involved.

I am happy to get a copy of the source code and make the correction and then test it on our system and then put it back into the git repository if someone could tell me how this should be done. Is this procedure documented? Could someone please tell me where to find the documentation?

We use our own git repositories for local code changes but I have never changed code in github.

Thanks,
John

**Comment by bloodstix** [comment]
Hey guys,
this is still an issue. I compiled on debian-stretch from sources and added --enable-command-args and put dont_blame_nrpe=1 in nrpe.cfg and changed the above mentioned line in nrpe.c, but the problem still persists.
What else can i do?

kind regards,
bloodstix

**Comment by Madlohe** [comment]
Hi @bloodstix, thanks for pointing this out.

Right now, I don't see any PRs or branches where this is fixed, so in the immediate term, you'll probably want to check out the code, make the change listed in the opening comment, and compile. I'm not sure what the exact timeline is for us, but I'd be surprised if there was another release for this project in the next 2-3 months

**Comment by bloodstix** [comment]
Hi @Madlohe,
as i wrote: I tryed the mentioned fix and it does not seem to work. I'm still getting my syslog spammed with The errors and got most checks for this host as "unknown"-State. Manually sending the requests Shows "0 byte received from host".

**Comment by Madlohe** [comment]
My apologies, I missed that part. Looking at your previous comment more carefully, it doesn't seem like you're having the same issue as the opening comment. "dont_blame_nrpe=1" seems to be working as expected for him. I would recommend opening a new issue with more detail about the exact issue you're experiencing.

**Comment by sop** [comment]
Hi!
I think this issue can be solved by a pull request #216.

**Comment by sawolf** [comment]
Fixed in next release
