### ISSUE TITLE
"Remote %s accepted a Version %s Packet", please add to debug

### ISSUE THREAD

**Issue by jobst** [NagiosEnterprises/nrpe#72]
Hi

When check_nrpe runs it fills the log quickly with "Remote %s accepted a Version %s Packet".
There is no way to turn it off other then excluding it in source, then recompiling it.
If you have lots of machines, the logs is filled quickly.

It would be nice if this would have a "debug" inclusion instead of printed all the time.
It is useful when debugging and finding out which service is Version 2 or 3, but not all the time.

Jobst

**Comment by jfrickson** [comment]
(Mostly) fixed in branch 'maint' via commit https://github.com/NagiosEnterprises/nrpe/commit/08425ff922b71a108da8bd457a9c63c3a20c04c6.

Please read the commit comment for an explanation of what I did and why. If you don't care for the changes as they are, post a comment here.

**Comment by cadtobias** [comment]
Issue still persistent. I excluded the part in /src/check_nrpe.c and recompiled. Nevertheless tha issue persists. I even backported the Buster nagios-nrpe-server 3.1.1 package but issue also persists.

Any recommendation?

**Comment by cadtobias** [comment]
Issue still persistent. I excluded the part in /src/check_nrpe.c and recompiled. Nevertheless tha issue persists. I even backported the Buster nagios-nrpe-server 3.1.1 package but issue also persists.

Any recommendation?

P.S. I recognize that commenting this ticket wasn't the proper way.

**Comment by hedenface** [comment]
@cadtobias I can look into this sometime today or tomorrow. I'll keep you posted.

**Comment by jobst** [comment]
I am the original poster of this bug.
I can confirm it has not been fixed.

**Comment by hedenface** [comment]
@cadtobias There must be something else at play here. Several us here attempted to reproduce your bug and were unable to. You aren't by chance running multiple versions of NRPE simultaneously are you? (Silly question I know, but the only thing that pops in my mind right now)

**Comment by cadtobias** [comment]
@hedenface I can tell that we run an Icinga2 topology with a Master server and about 4 satellites.
Each Icinga2 server writes massive log entries like:

`Jun 29 15:52:41 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Jun 29 15:52:41 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Jun 29 15:52:41 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Jun 29 15:52:41 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Jun 29 15:52:42 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Jun 29 15:52:42 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Jun 29 15:52:42 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx does not support Version 3 Packets
Jun 29 15:52:42 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
Jun 29 15:52:42 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 2 Packet
Jun 29 15:52:43 srv-satellite1 check_nrpe: Remote xxx.xxx.xxx.xxx accepted a Version 3 Packet
`
We run a mixed mode. The Icinga2 servers try to check via Nagios Vers 3 if that fails they try Vers 2.

Anymore else infos I can give you?

**Comment by cadtobias** [comment]
Thanks at all for the help. I now can confirm it has been fixed.
We had a custom directory with the check_nrpe file I didn't know of.
Therefore the check_nrpe file had never been replaced with the recompiled one after updateing nagios-nrpe-server / nagios-nrpe-plugin.
I exchanged the check_nrpe file manually with the one from buster nagios 3.1.1 backported version and now the logentries are dramatically reduced.

I apologize for the stress.

Cheers.
